### ISSUE TITLE
Alya missing line.png

### ISSUE THREAD

**Issue by mojamuto** [closebox73/Scorpio#11]
Using conky-manager2 I select the alya theme, and the following message appears in the terminal:

'conky: Unable to load image /.config/conky/Alya/res/line.png'.
conky: llua_do_call: function conky_draw_text execution failed: attempt to call a nil value

but the theme seems to work fine

![error](https://user-images.githubusercontent.com/36079583/184432381-e7205309-570d-4933-b8a6-a7a7b1aaab0a.png)

**Comment by closebox73** [comment]
actually it's not needed, I forgot to delete the line🤣
