### ISSUE TITLE
Lua Script aren't working.

### ISSUE THREAD

**Issue by Noob-linux-user** [closebox73/Scorpio#12]
I reinstall my linux mint distro and now Lua graphs aren't showing. Do I have to install some dependencies?
Also Can you please tell me how the greeting script work? I want to change a few things in it.

**Comment by closebox73** [comment]
execute this command
`conky --version`

scroll and do you see this?
![Scrot_23 01 23_06 43 28](https://user-images.githubusercontent.com/91961267/213946997-fdbc1424-15ff-449c-b7ab-9f1d8769db4b.png)

**Comment by Noob-linux-user** [comment]
This is what popped up.
there is no mentioning of Lua
`conky 1.10.8 compiled Mon Mar 23 06:55:20 UTC 2020 for Linux 4.4.0-176-generic x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * wireless
  * support for IBM/Lenovo notebooks
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xshape extension (click through)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * MPD
  * MOC

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
`

**Comment by closebox73** [comment]
Some time ago I also experienced this... the solution was I reinstalled conky with the command
`sudo apt install conky-all`
( I use Ubuntu )

**Comment by Noob-linux-user** [comment]
Oh, thank you. it worked 😄. 
Can we have a Conky script that shows different things based on the time? Same as the greeting script but instead of saying good morning or good evening something different. I tried to change that script but I didn't understand how it works.

**Comment by closebox73** [comment]
@Noob-linux-user of course you can, all you have to do is determine what the script changes based on? for example greeting.sh is based on the hour. please DM on my Twitter account, if it's a bit difficult to explain here
