### ISSUE TITLE
Conky does not show right time (0º null)

### ISSUE THREAD

**Issue by luisusquianomoreno** [closebox73/Scorpio#13]
![image](https://github.com/closebox73/Scorpio/assets/62809161/acfddd2f-a6fc-45b4-94c0-d3da577110fd)
Hi there!
https://www.youtube.com/watch?v=lXIb-1_H-mA
16:18

I followed these steps on this youtube video to install conky but it does not show the weather!
Instead of this, it shows a message saying this:
local time is null is 19.11
How can i fix this?

**Comment by closebox73** [comment]
Hi @luisusquianomoreno , This is due to api call restrictions, so for the themes that I have updated I have given a note to create your own OpenWeathermap api_key... you can see how to do it [here](https://github.com/closebox73/applying-theme) then overwrite old api_key in weather.sh
