### ISSUE TITLE
ghost

### ISSUE THREAD

**Issue by ghost03x** [closebox73/Scorpio#3]
![Screenshot from 2022-06-10 20-13-27](https://user-images.githubusercontent.com/92873829/173094880-56364f6b-1c7b-49b3-8d88-ccd7bcb6ad98.jpg)

Don't know whats the problem.....why there is a symbol A cap before the Degree Celsius ?

**Comment by closebox73** [comment]
this happens to some people, things to try are:
1. look for the degree symbol from another source and then overwrite the one in graias.conf
2. change the font config in graffias.conf

**Comment by ghost03x** [comment]
> this happens to some people, things to try are:
> 
>     1. look for the degree symbol from another source and then overwrite the one in graias.conf
> 
>     2. change the font config in graffias.conf

i think just copy the degree symbol and overwrite it...am i right?

**Comment by closebox73** [comment]
@ghost03x just change `${time %H.%M}` (line 72) to `${time %I.%M}` or `${time %I.%M %p}` if you want to show AM/PM

**Comment by ghost03x** [comment]
> @ghost03x just change `${time %H.%M}` (line 72) to `${time %I.%M}` or `${time %I.%M %p}` if you want to show AM/PM

UPDATE - now just swited to arch...everything is working perfectly...

**Comment by closebox73** [comment]
ah.. great 😊
