### ISSUE TITLE
background black

### ISSUE THREAD

**Issue by rizkhal** [closebox73/Scorpio#5]
```bash
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
```

![Screenshot from 2022-06-18 22-03-34](https://user-images.githubusercontent.com/24653114/174442026-f860e09c-324f-4ed2-88f7-50f3ef30381f.png)

How to remove background?

**Comment by closebox73** [comment]
ubah konfigurasi di Shaula.conf line 45
dari `own_window_argb_visual = false,`
menjadi `own_window_argb_visual = true,`

info kembali jika masih gagal

**Comment by rizkhal** [comment]
Makasi bang, udah bisa.
Btw saya kira tadi orang belanda ternyata orang indo ya bang.

Keren2 confignya bang

**Comment by closebox73** [comment]
@rizkhal perasaan tak kasih lokasi dari Miyagi jepang deh..
oke close ya
