### ISSUE TITLE
Themes don't work properly on arch linux with xfce.

### ISSUE THREAD

**Issue by Yittri** [closebox73/Scorpio#6]
Themes would appear as black boxes without icons and graphics. The process for fixing this was very long and un-intuitive. I'm making this issue for documentation purposes in case anyone else has similar problems. If there are easier ways to fix these problems, please let me know.

# Fixing transparency

  1. First make sure compositing is enabled in xfwm. To do this open `Settings Manager > Window Manager Tweaks > Compositor >   Enable Display Compositing` should be checked.
  2. In config file for the theme (for example for the Antares theme the config is in the root folder for that theme and called Antares.conf) change `own_window_argb_visual = false` to `own_window_argb_visual = true`

# Making icons render

  1. Move all the fonts in fonts file located in the theme folder to `~/.local/share/fonts`. If this folder does not exist, create it.
  2. In a terminal run `fc-cache`

# Making graphics appear

I'm assuming the graphics don't work properly because the themes expect for conky to be compiled with cairo which is not available in the repositories by default.
1.  In the aur download the PKGBUILD file for a package called conky-cairo. You can do this by running `yay -G conky-cairo` if you have yay installed. The file should be downloaded in a folder called conky-cairo.
2. In the PKGBUILD file edit line 25 from `pkgver=1.11.3` to `pkgver=1.12.2` or whatever the latest version of conky is.
3. If you're not using nvidia drivers change line 93 from `-D BUILD_NVIDIA=ON \` to `-D BUILD_NVIDIA=OFF \`.
4. In the same folder as the PKGBUILD file run `makepkg -si`. 

# Making conky start at login

1. In `Setting Manager > Session and Startup > Application Autostart` click on the + button. 
2. You can type anything in the name and description boxes but in the command box navigate to the `startup.sh` file for the theme.

All of this should make conky behave as expected.

**Comment by closebox73** [comment]
Wow,, thanks for taking the time to write that much, I'll add this to the installation instructions and put your name in the credits

regards
