### ISSUE TITLE
How to remove the A from the whether?

### ISSUE THREAD

**Issue by AdityaKukreti** [closebox73/Scorpio#9]
![Screenshot from 2022-07-18 18-12-26](https://user-images.githubusercontent.com/74974564/179513539-a31e96f2-bc89-41b2-8a06-d56c2b1d3655.png)
i want the temperature to be shown in celsius but that A character keeps on showing itself on the screen.

**Comment by closebox73** [comment]
sorry, until now it still hasn't been solved because I don't know the cause, and also it doesn't happen to everyone😔

**Comment by Tejas-117** [comment]
@AdityaKukreti Did you find any solution?

**Comment by AdityaKukreti** [comment]
> @AdityaKukreti Did you find any solution?

no i couldn't find any solutions

**Comment by closebox73** [comment]
@AdityaKukreti @Tejas-117
add a line to conky. config
```
override_utf8_locale = true,
```

someone in other issue solved the problem by doing this..

**Comment by AdityaKukreti** [comment]
> @AdityaKukreti @Tejas-117 add a line to conky. config
> 
> ```
> override_utf8_locale = true,
> ```
> 
> someone in other issue solved the problem by doing this..

thanks a lot!!
